/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.klasser;

import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Grupp4
 */
public class NewAgentPage extends javax.swing.JFrame {
    
    //HÃ¤r startar deklaration av fÃ¤lt.
    private InfDB idb;
    private int agentId;
    private String selectedAdminStatus;
    private String selectedAreaManager;
    private String selectedFieldAgent;
    private String selectedOfficeManager;
    private int selectedAreaToManage;
    private int selectedArea;
    //HÃ¤r slutar deklaration av fÃ¤lt.
    
    /**
     * Creates new form NewAlienPage
     */
    public NewAgentPage(InfDB idb, int agentId) {
        initComponents();
        this.idb = idb;
        this.agentId = agentId;
        addItemsToComboBoxes();
        addItemsToCmbFieldAgent();
        addItemsToCmbAreaId(cmbAreaId);
        addItemsToCmbAreaId(cmbAreaToManage);
        setTitle("Register new Agent!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewAlienHeader = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtAgentId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        lblAgentId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();
        lblAdminStatus = new javax.swing.JLabel();
        cmbAdminStatus = new javax.swing.JComboBox<>();
        lblFieldAgent = new javax.swing.JLabel();
        cmbFieldAgent = new javax.swing.JComboBox<>();
        cmbOfficeManager = new javax.swing.JComboBox<>();
        lblOfficeManager = new javax.swing.JLabel();
        cmbAreaToManage = new javax.swing.JComboBox<>();
        cmbAreaManager = new javax.swing.JComboBox<>();
        lblAreaManager = new javax.swing.JLabel();
        lblAreaToManage = new javax.swing.JLabel();
        cmbAreaId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNewAlienHeader.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblNewAlienHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewAlienHeader.setText("Register new agent");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblAgentId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAgentId.setText("Agent-ID:");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name:");

        lblPassword.setText("Password:");

        lblPhoneNumber.setText("Phone number:");

        lblArea.setText("Area:");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 255, 0));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblErrorMessage.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAdminStatus.setText("Admin Status:");

        cmbAdminStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAdminStatusActionPerformed(evt);
            }
        });

        lblFieldAgent.setText("Field Agent:");

        cmbFieldAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFieldAgentActionPerformed(evt);
            }
        });

        cmbOfficeManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOfficeManagerActionPerformed(evt);
            }
        });

        lblOfficeManager.setText("Office Mananger:");

        cmbAreaToManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaToManageActionPerformed(evt);
            }
        });

        cmbAreaManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaManagerActionPerformed(evt);
            }
        });

        lblAreaManager.setText("Area Mananger:");

        lblAreaToManage.setText("Area-ID to Manage:");

        cmbAreaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblNewAlienHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdminStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAgentId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAreaManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbAreaManager, 0, 90, Short.MAX_VALUE)
                                    .addComponent(txtAgentId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbAdminStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAreaToManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbAreaToManage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFieldAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOfficeManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTelefon)
                                    .addComponent(cmbFieldAgent, javax.swing.GroupLayout.Alignment.LEADING, 0, 90, Short.MAX_VALUE)
                                    .addComponent(cmbOfficeManager, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbAreaId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNewAlienHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneNumber)
                            .addComponent(txtAgentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgentId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName)
                            .addComponent(lblArea)
                            .addComponent(cmbAreaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword)
                            .addComponent(lblOfficeManager)
                            .addComponent(cmbOfficeManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdminStatus)
                            .addComponent(cmbAdminStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFieldAgent)
                            .addComponent(cmbFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbAreaManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAreaManager))
                        .addGap(27, 27, 27)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbAreaToManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAreaToManage))))
                .addGap(12, 12, 12)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Denna metod lägger till föremål (värden) i komboboxen.
     */
    private void addItemsToComboBoxes() {
        String firstOption = "No";
        String secondOption = "Yes";
        cmbAdminStatus.addItem(firstOption);
        cmbAdminStatus.addItem(secondOption);
        cmbAreaManager.addItem(firstOption);
        cmbAreaManager.addItem(secondOption);
        cmbOfficeManager.addItem(firstOption);
        cmbOfficeManager.addItem(secondOption);
    }
    
    /**
     * Denna metod lägger till föremål (värden) i komboboxen.
     */
    private void addItemsToCmbFieldAgent() {
        String firstOption = "Yes";
        String secondOption = "No";
        cmbFieldAgent.addItem(firstOption);
        cmbFieldAgent.addItem(secondOption);
    }
    
    /**
     * Denna metod stänger det aktuella fönstret samt öppnar ett nytt "AdminMenu" fönster. 
     * @param evt 
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
        new AdminMenu(idb, agentId).setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Denna metod använder sig av en metod från validation, som kontrollerar att alla fält som måste vara ifyllda är ifyllda.
     * samt lägger till en ny agent i databasen.
     * @param evt 
     */
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if(Validation.checkFourEmptyFields(txtAgentId, txtName, 
                txtPassword, txtTelefon)) {
            lblErrorMessage.setText("Every field has to be filled!");        
        }
        else if (Validation.checkIfTxtFieldIsOfInt(txtAgentId)) {
            try {
                int agentIdInt = parseInt(txtAgentId.getText());
                String name = txtName.getText();
                String phoneNumber = txtTelefon.getText();
                String password = txtPassword.getText();
                String sqlNewAgentQuery = "";
                
                if((selectedFieldAgent.equals("Yes")) && (selectedOfficeManager.equals("Yes"))) {
                    lblMessage.setText("");
                    lblErrorMessage.setText("The office manager can't be a field agent!");
                }
                else if((selectedAreaManager.equals("Yes")) && (selectedOfficeManager.equals("Yes"))) {
                    lblMessage.setText("");
                    lblErrorMessage.setText("The office manager can't be area manager!");
                }
                else if((selectedFieldAgent.equals("No")) && (selectedAreaManager.equals("No")) && (selectedOfficeManager.equals("No"))) {
                    lblMessage.setText("");
                    lblErrorMessage.setText("New agents must be atleast be a field agent!");
                }
                else {
                    if(selectedAdminStatus.equals("No")) {
                        sqlNewAgentQuery = "insert into Agent "
                            + "values(" + agentIdInt + ", '" + name + "', '" + phoneNumber + "', curdate(), 'N', '" + password + "', " + selectedArea + ");";
                    }
                    else if (selectedAdminStatus.equals("Yes")) {
                        sqlNewAgentQuery = "insert into Agent "
                            + "values(" + agentIdInt + ", '" + name + "', '" + phoneNumber + "', curdate(), 'J', '" + password + "', " + selectedArea + ");";
                    }
                    
                    idb.insert(sqlNewAgentQuery);
                    lblMessage.setText("Successful register!");
                    lblErrorMessage.setText("");
                    
                    if(selectedAreaManager.equals("Yes")) {
                        String sqlAreaManagerDeleteQuery = "delete from OmradesChef where Omrade = " + selectedAreaToManage + ";";
                        idb.delete(sqlAreaManagerDeleteQuery);
                        
                        String sqlAreaManagerInsertQuery = "insert into OmradesChef values(" + agentIdInt + ", " + selectedAreaToManage + ");";
                        idb.insert(sqlAreaManagerInsertQuery);
                        
                        String sqlFieldAgentQuery = "insert into Faltagent values(" + agentIdInt + ");";
                        idb.insert(sqlFieldAgentQuery);
                    }
                    else if((selectedFieldAgent.equals("Yes")) && (selectedAreaManager.equals("No"))) {
                        String sqlFieldAgentQuery = "insert into Faltagent values(" + agentIdInt + ");";
                        idb.insert(sqlFieldAgentQuery);
                    }
                    else if(selectedOfficeManager.equals("Yes")) {
                        if(LoginPage.checkForAnOfficeManager()) {
                            String sqlDeleteOfficeManagerQuery = "delete from Kontorschef;";
                            idb.delete(sqlDeleteOfficeManagerQuery);
                        }
                        String sqlInsertOfficeManagerQuery = "insert into Kontorschef values(" + agentIdInt + ", 'Örebrokontoret');";
                        idb.insert(sqlInsertOfficeManagerQuery);
                    }
                }
            }
            catch(InfException e) {
                lblErrorMessage.setText("Wrong ID format or Agent-ID already exist!");
            }
        }
        else {
            lblMessage.setText("");
            lblErrorMessage.setText("Agent-ID must be a number!");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed
    
    /**
     * I denna metod tilldelar man den nya agenten admin-status eller inte.
     * @param evt 
     */
    private void cmbAdminStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAdminStatusActionPerformed
        selectedAdminStatus = cmbAdminStatus.getSelectedItem().toString();
    }//GEN-LAST:event_cmbAdminStatusActionPerformed
    /**
     * I denna metod väljer man genom komboboxen om en agent ska vara områdeschef eller inte, om man är det kommer ett valalternativ presenteras för att
     * tilldela den nya agenten ett område.
     * @param evt 
     */
    private void cmbAreaManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaManagerActionPerformed
        selectedAreaManager = cmbAreaManager.getSelectedItem().toString();
        
        if(selectedAreaManager.equals("No")) {
            cmbAreaToManage.setVisible(false);
            lblAreaToManage.setVisible(false);
            cmbFieldAgent.setEnabled(true);
        }
        else {
            cmbAreaToManage.setVisible(true);
            lblAreaToManage.setVisible(true);
            cmbFieldAgent.setSelectedItem("Yes");
            cmbFieldAgent.setEnabled(false);
        }
    }//GEN-LAST:event_cmbAreaManagerActionPerformed
    /**
     * I denna metod tilldelar man den nya ageneten fältagent-status eller inte.
     * @param evt 
     */
    private void cmbFieldAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFieldAgentActionPerformed
        selectedFieldAgent = cmbFieldAgent.getSelectedItem().toString();
    }//GEN-LAST:event_cmbFieldAgentActionPerformed
    /**
     * I denna metod väljer man genom komboboxen om en agent ska vara kontorschef eller inte, om man är det kommer ett valalternativ presenteras för att
     * tilldela den nya agenten ett kontor.
     * @param evt 
     */
    private void cmbOfficeManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOfficeManagerActionPerformed
        selectedOfficeManager = cmbOfficeManager.getSelectedItem().toString();
    }//GEN-LAST:event_cmbOfficeManagerActionPerformed
    /**
     * I denna metod tilldelar man agenten vilket område den skall vara verksam i som chef.
     * @param evt 
     */
    private void cmbAreaToManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaToManageActionPerformed
        String selectedAreaToManageString = cmbAreaToManage.getSelectedItem().toString();
        selectedAreaToManage = parseInt(selectedAreaToManageString);
    }//GEN-LAST:event_cmbAreaToManageActionPerformed
    /**
     * I denna metod tilldelar man agenten ett områdes-id.
     * @param evt 
     */
    private void cmbAreaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaIdActionPerformed
        String selectedAreaString = cmbAreaId.getSelectedItem().toString();
        selectedArea = parseInt(selectedAreaString);
    }//GEN-LAST:event_cmbAreaIdActionPerformed
    /**
     * I denna metod läggs de områdes-id som finns till i komboboxen.
     * @param fillThisBox 
     */
    private void addItemsToCmbAreaId(JComboBox<String> fillThisBox) {
        try {
            String sqlQuestion = "select Omrades_ID from Omrade";
            ArrayList<String> areaIdList = idb.fetchColumn(sqlQuestion);
            for(String anAreaId : areaIdList) {
                fillThisBox.addItem(anAreaId);
            }
        }
        catch(InfException e) {
            JOptionPane.showMessageDialog(null, "Internal database error!");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbAdminStatus;
    private javax.swing.JComboBox<String> cmbAreaId;
    private javax.swing.JComboBox<String> cmbAreaManager;
    private javax.swing.JComboBox<String> cmbAreaToManage;
    private javax.swing.JComboBox<String> cmbFieldAgent;
    private javax.swing.JComboBox<String> cmbOfficeManager;
    private javax.swing.JLabel lblAdminStatus;
    private javax.swing.JLabel lblAgentId;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblAreaManager;
    private javax.swing.JLabel lblAreaToManage;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblFieldAgent;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewAlienHeader;
    private javax.swing.JLabel lblOfficeManager;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JTextField txtAgentId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
